---
name: module3_task1

"on":
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: run setup.sh
        run: |
          cd module3_task1
          chmod u+x setup.sh
          sudo ./setup.sh
      - name: lint
        run: make  lint
      - name: build
        run: make build
      - name: unit-tests
        run: make unit-tests
      - name: validate
        run: make validate
      - name: integration-tests
        run: make unit-tests
...
