name: release_drafter
"on":
  push:
    tags: "1.0.1"
    branches: master
  pull_request:
    branches: master
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-18.04

    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: "CHANGELOG"
          output: CHANGELOG.md

