---
name: module3_task3

"on":
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - name: Archive
        run: echo ${{ github.sha }} >> Archive.txt
      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            awesome-website.zip
            DEPLOY.md
      - name: run setup.sh
        run: |
          cd module3_task3
          chmod u+x setup.sh
          ./setup.sh
      - name: make lint
        run: |
          cd module3_task3
          make lint
      - name: make build
        run: |
          cd module3_task3
          make build
      - name: make unit-tests
        run: |
          cd module3_task3
          make unit-tests
      - name: make validate
        run: |
          cd module3_task3
          make validate
      - name: make integration-tests
        run: |
          cd module3_task3
          make integration-tests
      - name: make package
        run: |
          cd module3_task3
          make package
...
