---
name: module3_task3

"on":
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: run setup.sh
        run: |
          cd module3_task3
          chmod u+x setup.sh
          ./setup.sh
      - name: make lint
        run: |
          cd module3_task3
          make lint
      - name: make build
        run: |
          cd module3_task3
          make build
      - name: make unit-tests
        run: |
          cd module3_task3
          make unit-tests
      - name: make validate
        run: |
          cd module3_task3
          make validate
      - name: make integration-tests
        run: |
          cd module3_task3
          make integration-tests
      - name: make package
        run: |
          cd module3_task3
          make package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md
      - name: Archive
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module3_task3/awesome-website.zip
...
